apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toolva-data-pvc
  namespace: toolva
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
